# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rautomation}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jarmo Pertman"]
  s.date = %q{2010-10-14}
  s.description = %q{RAutomation tries to be a small and easy to use library for helping out to automate windows and their controls
for automated testing.

RAutomation aims to provide:
* Easy to use and user-friendly API (inspired by Watir http://www.watir.com).
* Cross-platform compatibility
* Easy extensibility - have some application, which uses some specialized technology, but isn't supported by RAutomation?
  You can get dirty and create new implementation for RAutomation, due to the applied Strategy Pattern!}
  s.email = %q{jarmo.p@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ext/AutoItX/AutoItX.chm",
     "ext/AutoItX/AutoItX3.dll",
     "lib/rautomation.rb",
     "lib/rautomation/button.rb",
     "lib/rautomation/implementations/autoit.rb",
     "lib/rautomation/implementations/autoit/button.rb",
     "lib/rautomation/implementations/autoit/locators.rb",
     "lib/rautomation/implementations/autoit/text_field.rb",
     "lib/rautomation/implementations/autoit/window.rb",
     "lib/rautomation/implementations/helper.rb",
     "lib/rautomation/text_field.rb",
     "lib/rautomation/wait_helper.rb",
     "lib/rautomation/window.rb",
     "rautomation.gemspec",
     "spec/button_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/test.html",
     "spec/text_field_spec.rb",
     "spec/window_spec.rb"
  ]
  s.homepage = %q{http://github.com/jarmo/RAutomation}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Automate windows and their controls through user-friendly API with Ruby}
  s.test_files = [
    "spec/button_spec.rb",
     "spec/spec_helper.rb",
     "spec/text_field_spec.rb",
     "spec/window_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

