require "win32ole"
require File.dirname(__FILE__) + "/autoit/locators"
require File.dirname(__FILE__) + "/autoit/button"
require File.dirname(__FILE__) + "/autoit/text_field"
require File.dirname(__FILE__) + "/autoit/window"
