begin
  gem "ffi"
rescue Gem::LoadError
  raise Gem::LoadError, "Unable to load FFI gem. Install it with:\n\tgem install ffi"
end
require "ffi"
require File.dirname(__FILE__) + "/ms_uia/constants"
require File.dirname(__FILE__) + "/ms_uia/keystroke_converter"
require File.dirname(__FILE__) + "/ms_uia/functions"
require File.dirname(__FILE__) + "/ms_uia/locators"
require File.dirname(__FILE__) + "/ms_uia/window"
require File.dirname(__FILE__) + "/ms_uia/button_helper"
require File.dirname(__FILE__) + "/ms_uia/control"
require File.dirname(__FILE__) + "/ms_uia/button"
require File.dirname(__FILE__) + "/ms_uia/checkbox"
require File.dirname(__FILE__) + "/ms_uia/radio"
require File.dirname(__FILE__) + "/ms_uia/text_field"
require File.dirname(__FILE__) + "/ms_uia/select_list"
require File.dirname(__FILE__) + "/ms_uia/table"
require File.dirname(__FILE__) + "/ms_uia/label"
require File.dirname(__FILE__) + "/ms_uia/list_box"
